Models/ErrorViewModel.cs
namespace ConsumindoAPIDeGames.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MagicCardsViewModel.cs
namespace ConsumindoAPIDeGames.Model
{
    public class MagicCardsViewModel
    {
        public List<Card> cards { get; set; }
    }

    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class Card
    {
        public string name { get; set; }
        public string manaCost { get; set; }
        public double cmc { get; set; }
        public List<string> colors { get; set; }
        public List<string> colorIdentity { get; set; }
        public string type { get; set; }
        public List<string> types { get; set; }
        public List<string> subtypes { get; set; }
        public string rarity { get; set; }
        public string set { get; set; }
        public string setName { get; set; }
        public string text { get; set; }
        public string artist { get; set; }
        public string number { get; set; }
        public string power { get; set; }
        public string toughness { get; set; }
        public string layout { get; set; }
        public string multiverseid { get; set; }
        public string imageUrl { get; set; }
        public List<string> variations { get; set; }
        public List<ForeignName> foreignNames { get; set; }
        public List<string> printings { get; set; }
        public string originalText { get; set; }
        public string originalType { get; set; }
        public List<Legality> legalities { get; set; }
        public string id { get; set; }
        public string flavor { get; set; }
        public List<Ruling> rulings { get; set; }
        public List<string> supertypes { get; set; }
    }

    public class ForeignName
    {
        public string name { get; set; }
        public string text { get; set; }
        public string type { get; set; }
        public string flavor { get; set; }
        public string imageUrl { get; set; }
        public string language { get; set; }
        public int multiverseid { get; set; }
    }

    public class Legality
    {
        public string format { get; set; }
        public string legality { get; set; }
    }


    public class Ruling
    {
        public string date { get; set; }
        public string text { get; set; }
    }


}

Controllers/CardsController.cs
using ConsumindoAPIDeGames.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using X.PagedList;

namespace ConsumindoAPIDeGames.Controllers
{
    public class CardsController : Controller
    {
        private readonly string ENDPOINT = "https://api.magicthegathering.io/v1/cards";
        private readonly HttpClient _httpClient = null;
        private static List<Card> _cards = null;

        public CardsController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri(ENDPOINT);
        }
        public async  Task<IActionResult> Index(int? page)
        {
            var itemsByPage = 10;
            var currentPage = page ?? 1;


            try
            {
                MagicCardsViewModel cardList = null;
                _cards = new List<Card>();

                var response = await _httpClient.GetAsync(ENDPOINT);

                if (response.IsSuccessStatusCode) {
                    string content = await response.Content.ReadAsStringAsync();
                    cardList = JsonConvert.DeserializeObject<MagicCardsViewModel>(content);

                    foreach(var card in cardList.cards)
                    {
                        _cards.Add(card);
                    }
                }
                else
                {
                    ModelState.AddModelError(null, "Erro ao processar o Magic!");
                }
                return View(await cardList.cards.ToPagedListAsync(currentPage, itemsByPage));
            }
            catch (Exception ex)
            {
                String msg = ex.Message;
                throw;
            }

            //return View(cardList.cards);
        }
        [HttpGet]
        public IActionResult Details(string id)
        {
            Card card = _cards.FirstOrDefault(c => c.id.Equals(id));
            return View(card);
        }
    }
}

Controllers/HomeController.cs
using ConsumindoAPIDeGames.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsumindoAPIDeGames.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cards/Details.cshtml
@model ConsumindoAPIDeGames.Model.Card

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Card</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.manaCost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.manaCost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cmc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cmc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rarity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rarity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.set)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.set)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.setName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.setName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.artist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.power)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.power)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.toughness)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.toughness)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.layout)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.layout)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.multiverseid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.multiverseid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imageUrl)
        </dt>
        <dd class = "col-sm-10">
            <img src=" @Html.DisplayFor(model => model.imageUrl)" alt="image"        
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.originalText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.originalText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.originalType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.originalType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.flavor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.flavor)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Cards/Index.cshtml
@model X.PagedList.IPagedList<ConsumindoAPIDeGames.Model.Card>

@using X.PagedList.Mvc.Core;


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Mana Cost
            </th>
            <th>
                Cmc
            </th>
            <th>
                Type
            </th>
            <th>
                Rarity
            </th>
            <th>
                Set
            </th>
            <th>
                Set Name
            </th>
            <th>
                Number
            </th>
            <th>
                Power
            </th>
            <th>
                Toughness
            </th>
            <th>
                Layout
            </th>
            <th>
                Multiverseid
            </th>
            <th>
                Image Url
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.manaCost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cmc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.rarity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.set)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.setName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.power)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.toughness)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.layout)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.multiverseid)
            </td>
            <td>
                    <img src="@Html.DisplayFor(modelItem => item.imageUrl)" alt="image" />
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new {id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

@Html.PagedListPager(Model, page => Url.Action("index", new {page}))

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConsumindoAPIDeGames</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsumindoAPIDeGames.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ConsumindoAPIDeGames</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cards" asp-action="Index">Cards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ConsumindoAPIDeGames - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>